version: '2'
services:
  web:
    build: .
    ports:
     - "8800:80"
    volumes:
     - .:/code
    depends_on:
     - node
     - redis
    extra_hosts:
     - "parenthost:172.17.0.1"
  node:
    image: node:5.2
  redis:
    image: redis:3.2.2
    ports:
     - "6379:6379"

